name: ChangePlayerSkin
version: '${version}'
main: tech.inudev.changeskin.ChangeSkin
api-version: 1.17
authors: [ kumitatepazuru ]
description: スキンをいじくり回せるプラグインです
website: https://www.inu-dev.tech/
commands:
  reloadskin:
    description: スキンをリロードします
    permission: changeskin.reload

permissions:
  changeskin.reload:
    description: スキンをリロードする権限
    default: op
